name: Run on PR comment

on:
  pull_request:
    types: [opened, reopened]
    paths: ['**.puml', '**.pml']

jobs:
  comment-puml:
    runs-on: ubuntu-latest
    name: Comment new diagrams
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19

      - name: Comment on PR
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
