name: Run on PR comment

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened]
    paths: ['**.puml', '**.pml']

jobs:
  comment-puml:
    runs-on: ubuntu-latest
    name: Comment new diagrams
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19

      - name: install axios
        run: yarn add axios

      - name: Comment on PR
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            const axios = require('axios')

            async function getPuml(hex) {
                const resp = await axios.get('https://www.plantuml.com/plantuml/txt/~h' + hex)
                return resp.data
            }

            function encodePuml(raw) {
                return Buffer.from(raw).toString('hex')
            }

            function readFile(path) {
                return fs.readFileSync(path).toString()
            }

            async function getPumlForPath(path) {
                const contents = readFile(path)
                const encoded = encodePuml(contents)
                const puml = await getPuml(encoded)
                return '```\n' + puml + '\n```'
            }

            const files = '${{ steps.changed-files.outputs.all_changed_files }}'



            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Fade me fam'
            })
